export const studioCopy = {
  login: {
    eyebrow: "Acceso al Studio",
    title: "Studio",
    description:
      "Un lugar enfocado para dar forma a ideas, preparar Markdown y publicar con confianza.",
    formTitle: "Bienvenido de nuevo",
    formDescription: "Usa tus credenciales privadas de Studio para continuar.",
    usernameLabel: "Usuario",
    usernamePlaceholder: "studio",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Ingresa tu contraseña",
    submit: "Entrar al Studio",
    invalidCode: "Las credenciales no son correctas.",
    circuitTitle: "Líneas decorativas de circuito",
    publicSite: "Sitio público",
  },
  shell: {
    brand: "Studio",
    owner: "Alberto Avendaño",
    dashboard: "Resumen",
    writing: "Publicaciones",
    logout: "Cerrar sesión",
    publicSite: "Sitio público",
    navigationLabel: "Navegación del Studio",
    dashboardLabel: "Panel del Studio",
    collapseSidebar: "Contraer barra lateral",
    expandSidebar: "Expandir barra lateral",
    skipToContent: "Ir al contenido del Studio",
  },
  dashboard: {
    eyebrow: "Panel de control",
    title: "Buenos días, Alberto.",
    description:
      "Aquí tienes una vista general de tu actividad editorial y del estado del Studio.",
    newPost: "Escribir una nueva publicación",
    viewBlog: "Ver blog público",
    openDesk: "Abrir editor",
    metricsLabel: "Actividad del Studio",
    publishQueue: "Borradores pendientes",
    latestSignal: "Canal publicado",
    pipelineTitle: "Flujo editorial",
    pipelineDescription: "Las publicaciones más recientes del Studio.",
    noPostsTitle: "Inicia el flujo editorial",
  },
  blog: {
    eyebrow: "Editor de publicaciones",
    title: "Escribe en Markdown. Publica cuando esté listo.",
    description:
      "Crea borradores, traduce, agrega portadas o imágenes en línea y publica mediante Argos.",
    viewPublicBlog: "Ver blog público",
    createTitle: "Crear una nueva publicación",
    createDescription:
      "Empieza por la historia. Todo se guarda como borrador hasta que decidas publicarlo.",
    draftHint:
      "La recuperación local permanecerá activa hasta guardar el borrador. Guardarlo no lo publica.",
    savedNotice: "Cambios guardados. Studio y Argos están sincronizados.",
    unsavedWarning: "Tienes cambios sin guardar en esta publicación.",
    basicsTitle: "Datos principales",
    distributionTitle: "Distribución",
    contentTitle: "Contenido",
    titleLabel: "Título",
    titlePlaceholder: "Un título de trabajo claro",
    slugLabel: "Slug de la URL",
    slugPlaceholder: "post-url-slug",
    slugHelp: "Usa solo letras minúsculas, números y guiones.",
    localeLabel: "Idioma",
    categoryLabel: "Categoría",
    categoryPlaceholder: "Ingeniería",
    tagsLabel: "Etiquetas",
    tagsPlaceholder: "nestjs, producto, automatización",
    coverLabel: "Imagen de portada",
    noCover: "Sin portada",
    featuredLabel: "Destacar esta publicación en el blog público",
    excerptLabel: "Extracto",
    excerptPlaceholder: "Un resumen breve para tarjetas y buscadores…",
    bodyLabel: "Contenido en Markdown",
    bodyPlaceholder:
      "Empieza a escribir… Usa encabezados, listas, enlaces, bloques de código e imágenes subidas.",
    bodyHelp:
      "Se admiten encabezados, listas, enlaces, código e imágenes en línea. Pega el fragmento de la biblioteca de imágenes donde corresponda.",
    saveDraft: "Guardar borrador",
    savingDraft: "Guardando borrador…",
    publish: "Publicar",
    publishing: "Publicando…",
    unpublish: "Volver a borrador",
    unpublishing: "Volviendo a borrador…",
    unpublishConfirmation:
      "¿Quieres devolver esta publicación a borrador? Desaparecerá del blog público.",
    editPublished: "Editar publicación",
    saveChanges: "Guardar cambios",
    savingChanges: "Guardando cambios…",
    previewPost: "Abrir publicación",
    queueTitle: "Borradores",
    queueDescription: "Revisa, mejora y publica el trabajo en curso.",
    noDraftsTitle: "No hay borradores pendientes",
    noDraftsBody: "Crea una publicación arriba y aparecerá aquí para revisión.",
    publishedTitle: "Publicadas",
    noPublishedTitle: "Aún no hay publicaciones",
    noPublishedBody: "Tu primera publicación aparecerá aquí.",
    assetsTitle: "Biblioteca de imágenes",
    assetsDescription:
      "Sube archivos JPEG, PNG, WebP o AVIF; luego úsalos como portada o pega su Markdown en la publicación.",
    assetAltLabel: "Texto alternativo",
    assetAltPlaceholder: "Describe lo que comunica la imagen…",
    assetAltHelp: "Escribe para alguien que no puede ver la imagen.",
    assetFileLabel: "Archivo de imagen",
    uploadAsset: "Subir imagen",
    uploadingAsset: "Subiendo imagen…",
    markdownSnippet: "Fragmento Markdown",
    noAssets: "Aún no hay imágenes",
    noAssetsBody:
      "Sube aquí la primera imagen. Studio generará el Markdown por ti.",
    assetsUnavailableTitle: "Biblioteca no disponible",
    checklistEyebrow: "Antes de publicar",
    checklistTitle: "Lista de publicación",
    backendUnavailable:
      "El recurso administrativo de Argos no está disponible en este entorno.",
  },
};

export const studioBlogChecklist = [
  "El título y el extracto se entienden con claridad",
  "La portada y las imágenes tienen texto alternativo útil",
  "Los enlaces y bloques de código se muestran correctamente",
  "El slug, el idioma y la categoría son definitivos",
];
