services:
  web:
    build:
      context: .
      target: deps
    command: npm run dev -- --hostname 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - ARGOS_API_URL=http://host.docker.internal:5000/api
      - NEXT_PUBLIC_ARGOS_API_URL=http://localhost:5000/api
